let data = {
  Home: [
    "Als Deutsch - Afrikanische Begegnungsstätte gegründet, nahm das Oromo Horn von Afrika Zentrum bereits im Jahre 1985 seine Tätigkeit in Berlin-Wedding auf und ist damit einer der ältesten und renommiertesten Vereine für Migration in Berlin.",
    "Die Aufgabe des Vereins ist damals wie heute die Förderung von Akzeptanz in einer multikulturellen Gesellschaft, in der die erfolgreiche Gestaltung von Integration Gleichheit für alle bedeutet",
    "Das Oromo Horn von Afrika Zentrum gilt als Anlaufstelle in allen Bereichen der Integrationshilfe, als Orientierungspunkt für Geflüchtete und leistet aktive Hilfe zur Verbesserung der Migration.",
    "Der Verein unterstützt bei Behördengängen, z.B. beim Sozialamt, der Ausländerbehörde oder dem Jobcenter, bietet Übersetzungsarbeit bei Formalien, individuelle Beratung und hilft bei der Vermittlung von Rechtsbeistand.",
    "Neben einem Sprachtraining fördert das Zentrum Schulprojekte und leitet Seminare zur Sensibilisierung für ethnische Minderheiten in Deutschland.",
    "Das Oromo Horn von Afrika Zentrum steht auch für die Erhaltung von Werten und Wurzeln der Migranten aus den verschiedensten Teilen Afrikas, die im Austausch und Begegnungen gepflegt werden. Ein Schwerpunkt des Zentrums gilt auch der Aufklärung über das Volk der Oromo, die Ureinwohner Ostafrikas. Welches mit ca. 50 Millionen Menschen die zweitgrößte Volksgruppe in Afrika darstellt und die seit der Kolonialisierung ihres Landes immer wieder massiven Menschenrechtsverletzungen ausgesetzt ist. ",
  ],
  Angebot: {
    beratung: [
      "Öffnungszeiten: Montag - Mittwoch - Donnerstag 11:00 - 15:00",
      "Tetrmin nur nach telefonische oder per E- Mail",
      "Telefon: 030- 4941036",
      "E- Mail: oromocenter@oromo-deutsch.de",
    ],
    Somali_beratung: [
      "Wir bieten Flüchtlingen in Notsituationen Unterkunft und Verpflegung, insbesondere für diejenigen die vom Horn von Afrika kommen.",
      "Darüber hinaus gibt es Hilfe für Flüchtlinge und Asylbewerber von der Antragsstellung bei der Ausländerbehörde bis zur Klärung aller Formalien.",
      "Es findet eine enge Zusammenarbeit mit dem Flüchtlingsrat Berlin/Brandenburg statt.",
    ],
    Flüchtlingsbegleiterinnen: [
      "Die Qualifizierung zum Flüchtlingsbegleiter*in",
      'Ein "Flüchtlingsbegleiter *in " kann Geflüchtete bei Behördengängen, dem Gang zu Ämtern, Krankenhäusern, Job Center etc. begleiten. In der Schulung soll eine Flüchtlingsbegleiter*in u.a. auf den Umgang mit Rassismus vorbereitet werden, einfaches rechtliches Grundlagenwissen bekommen, sie sollen lernen, wie sie anderen die Angst vor dem Formular-ausfüllen nehmen können und außerdem was eine gute Bewerbung ausmacht und wie sie andere bei dem Bewerben unterstützen können. Auch hier sind die Teilnehmenden selbst gefragt ihre Erwartungen einzubringen.',
      "Die Flüchtlingsbegleiter*innen und Flüchtlingsfürsprecher*innen werden sich weiterhin treffen und austauschen sowie sich an Folgeterminen weiter qualifizieren. ",
      "Die Teilnehmer*innen erhalten für ihren Einsatz bzw. Auftritt als Flüchtlingsbegleiter*in und Flüchtlingsfürsprecher*in eine Vergütung als Honorar.",
      "Wir bitten alle Interessierte sich telefonisch an uns zu wenden. ",
      "Tel. 030-4941036 ( Montag-Mittwoch-Donnerstag 11.00 - 15:00 )",
      "E-Mail: oromocenter@oromo-deutsch.de",
    ],
    Schulprojekttage: [
      "Das Projekt „Entwicklung einer herkunftslandübergreifenden Kooperation“ bietet Schulen Projekttage zu folgenden Themen an:",
      "1.Fluchtursache – Asylbewerber/Flüchtlinge und ihre Lebenssituationen",
      "2.Kulturelle Vielfalt und interkulturelle Kompetenzen",
      "3.Was hat mein Handy mit Afrika zu tun?",
      "Diese Veranstaltungen werden in Kooperation mit unseren Partnern  dem Bund für interkulturelle Sensibilisierung und Bildungsarbeit in der Bundesrepublik Deutschland und mit unserem Oromo „Horn von Afrika“ Zentrum durchgeführt.",
      "Die Veranstaltungsreihen bzw. Projekttage zielen darauf ab, Verständnis für Flüchtlinge, deren Motive für ihre Flucht aus ihren Heimatländern und ihren Situationen in den Asylbewerberheimen zu verdeutlichen und zu erklären und mit den Schüler/Innen und Jugendlichen in eine entsprechende Diskussion einzutreten.",
      "Dies soll dazu führen, Zuwendungen für verschiedene Kulturen und Lebensweisen zu entwickeln, sowie einen Beitrag zum Abbau von Vorurteilen und Diskriminierung gegenüber Minderheiten zu leisten.",
      "Sie fördern somit die antirassistische und interkulturelle Erziehung der Schüler/Innen und Jugendlichen.",
      "Die Schüler/Innen und Jugendlichen sollen sich aktiv in die Auseinandersetzung zu den Fluchtursachen und interkulturellen Kompetenzen einbringen, sowie als Vermittler von antirassistischen und diskriminierungsfreien Verhaltensweisen wirken.",
      "Im Rahmen Ihrer Projekttage und -wochen, sowie zur Ergänzung von Sozialkunde- und Geschichtsunterricht können die Schüler/Innen und Jugendlichen ab Klasse 7 dieses Bildungs- und Aufklärungsangebot nutzen.",
      "Die Veranstaltungen werden von erfahrenden Referenten durchgeführt und finden direkt in Ihrer Schule statt.",
      "Bei Interesse können die Veranstaltungen ebenfalls im Oromo Horn für Afrika Zentrum durchgeführt werden. Bei der Durchführung dieser Veranstaltungen in diesen Zentren können sich die Schüler/Innen und Jugendlichen gleichzeitig einen Überblick über die Arbeit der Vereine verschaffen und konkret mit jungen Flüchtlingen über deren Probleme diskutieren.",
      "Mail:  oromocenter@oromo-deutsch.de",
      "Telefon: 030-4941036 / 01723141063",
      "Interkulturelles Computerzentrum",
      "Öffnungszeiten:",
      "Montag - Mittwoch - Donnerstag: 11-15 Uhr",
      "Wir stellen Dir einen Computer mit Internet zur Verfügung, an dem Du Dich für Bewerbung, Ausbildung und Beruf informieren und ausprobieren kannst.",
      "Zusätzlich bekommst Du von uns: Hilfe und Unterstützung bei der Findung Deines Ausbildungs- und Arbeitsplatzes.",
      "Sprachvermittllung und Übersetzung für: Oromo Sprache, Somalisch, Amharisch, Englisch und Deutsch",
    ],
  },
  Ausrichtung: {
    Aufgaben: [
      "Unterstützung von Flüchtlingen und Migranten",
      "Integrationshilfe",
      "Hilfe zur Selbsthilfe",
      "Austausch zwischen Menschen unterschiedlicher Kulturen",
      "Beitrag zur Völkerverständigung",
      "Förderung der kulturellen Identität und Integration von ethnischen Gruppen, insbesondere solcher aus der Region vom Horn von Afrika ",
    ],
    Angebote: [
      "Soziale Beratung und Betreuung für Flüchtlinge und Migranten",
      "Unterstützung bei Behördengängen ( Jobcenter, Sozialamt, Ausländerbehörde )",
      "Übersetztungen von Formalien",
      "Vermittlung von Rechtsbeistand",
      "Sensibilisierungsseminare ",
      "Antirassistische Aufklärungsarbeit an Schulen und Polizeischulen",
      "Vermittlung von Know-how für Migrantenfrauen",
      "Beratung bei der Berufsfindung für Jugendliche",
      "Nachhilfeunterricht für Kinder mit Migrationshintergrund",
      "Oromo-Sprachunterricht für Kinder",
      "Sprachvermittllung und Übersetzung für:Oromo Sprache, Amharisch, Englisch und Deutsch",
    ],
    Schwerpunkte: [
      "Flüchtlingsberatung und -betreuung",
      "Hilfe für Menschen mit Migrationshintergrund",
      "Integrations- und Bildungsarbeit",
      "Interkulturelle Begegnung",
      "Seminare zu Menschenrechtsfragen und Fluchtursachen",
      "Förderung der Oromo-Kultur und Sprache",
      "Information und Vernetzung für Oromo-Organisationen",
    ],
  },
};

export default data;
